package com.backpack.BackpackTravelApp.response.fragment;

public class LIST_SERVICE_FEES_GROUP {
    LIST_SERVICE_FEE_REFS LIST_SERVICE_FEE_REFSObject;
    LIST_SERVICE_COVERAGE_INFO_GROUP LIST_SERVICE_COVERAGE_INFO_GROUPObject;
    ArrayList<Object> LIST_SERVICE_DETAILS_GROUP = new ArrayList<Object>();
    private String TYPE;
    LIST_SERVICE_FEE_INFO_GROUP LIST_SERVICE_FEE_INFO_GROUPObject;


    // Getter Methods

    public LIST_SERVICE_FEE_REFS getLIST_SERVICE_FEE_REFS() {
        return LIST_SERVICE_FEE_REFSObject;
    }

    public LIST_SERVICE_COVERAGE_INFO_GROUP getLIST_SERVICE_COVERAGE_INFO_GROUP() {
        return LIST_SERVICE_COVERAGE_INFO_GROUPObject;
    }

    public String getTYPE() {
        return TYPE;
    }

    public LIST_SERVICE_FEE_INFO_GROUP getLIST_SERVICE_FEE_INFO_GROUP() {
        return LIST_SERVICE_FEE_INFO_GROUPObject;
    }

    // Setter Methods

    public void setLIST_SERVICE_FEE_REFS(LIST_SERVICE_FEE_REFS LIST_SERVICE_FEE_REFSObject) {
        this.LIST_SERVICE_FEE_REFSObject = LIST_SERVICE_FEE_REFSObject;
    }

    public void setLIST_SERVICE_COVERAGE_INFO_GROUP(LIST_SERVICE_COVERAGE_INFO_GROUP LIST_SERVICE_COVERAGE_INFO_GROUPObject) {
        this.LIST_SERVICE_COVERAGE_INFO_GROUPObject = LIST_SERVICE_COVERAGE_INFO_GROUPObject;
    }

    public void setTYPE(String TYPE) {
        this.TYPE = TYPE;
    }

    public void setLIST_SERVICE_FEE_INFO_GROUP(LIST_SERVICE_FEE_INFO_GROUP LIST_SERVICE_FEE_INFO_GROUPObject) {
        this.LIST_SERVICE_FEE_INFO_GROUPObject = LIST_SERVICE_FEE_INFO_GROUPObject;
    }
}
